#!/bin/bash
WEBRTC_TARGET="libjingle_peerconnection_so"

GYP_DEFINES="\
OS=linux \
host_os=linux \
build_with_libjingle=1 \
build_with_chromium=0 \
clang=1 \
enable_tracing=1 \
disable_iterator_debugging=1 \
disable_glibcxx_debug=1 \
target_arch=arm \
arm_version=7 \
arm_float_abi=hard \
arm_neon=1 \
arm_thumb=0 \
use_rtti=1 \
"

GYP_CROSSCOMPILE=1
