#!/usr/bin/env python
"""
Generates inventory for vagrant machine(s).
"""
import json
import logging
import os
import re

import netaddr
import vagrant


class Vagrant(vagrant.Vagrant):
    
    PRIVATE_IPV4_RE = r"\s+inet\s+(?P<cidr>\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}/\d{1,2})\s+"
    
    def private_ipv4(self, iface, vm_name=None):
        command = 'ip addr show {0}'.format(iface)
        output = self._run_vagrant_command(['ssh', vm_name, '-c', command])
        m = re.search(self.PRIVATE_IPV4_RE, output)
        if m is None:
            raise Exception(
                'No ipv4 returned by "{command}"-\n{output}'
                .format(command=command, output=output)
            )
        return str(netaddr.IPNetwork(m.group('cidr')).ip)


def main():
    root = os.path.abspath(os.path.join(os.path.basename(__file__), '..'))
    v = Vagrant(root=root)
    machine_name = 'default'
    inventory = {
        machine_name: {
            'hosts': [v.private_ipv4('eth1', machine_name)],
            'vars': {
                'ansible_ssh_user': v.user(machine_name),
                'ansible_ssh_private_key_file': v.keyfile(machine_name),
            },
        },
    }
    print json.dumps(inventory, indent=4)


if __name__ == '__main__':
    main()
